//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace haunted_castle.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("haunted_castle.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon appicon {
            get {
                object obj = ResourceManager.GetObject("appicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ``````````````````````````````````````````````````````````````````````````````````r
        ///`````````````````````````````````````````|Zz``````````````````````````````````````r
        ///````````````*`````*``````````*```````````|``````````*``````````*`````*````````````r
        ///````````````````````C````````````*``````21``````*````````````````*````````````````r
        ///`````````````````````````*`````````````2121`````````````*````*````````````````````r
        ///```````````````*``````````````*```````212121```````*``````````````*```````````````r
        ///`` [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ASCII_Art {
            get {
                return ResourceManager.GetString("ASCII_Art", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a```````````````````````````````````r
        ///a```````````````````````````````````r
        ///a```````````````````````````````````r
        ///a```````````````````````````````````r
        ///a```##########```````#############``r
        ///a````####`````##`````##```###```##``r
        ///a`````###``````##````#````###````#``r
        ///a`````###``````##`````````###```````r
        ///a`````###``````##`````````###```````r
        ///a`````###`````##``````````###```````r
        ///a`````########````````````###```````r
        ///a`````###``##`````````````###```````r
        ///a`````###```##````````````###```````r
        ///a```` [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Razorteeth {
            get {
                return ResourceManager.GetString("Razorteeth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to === ESCAPE FROM THE HAUNTED CASTLE ===
        ///
        ///Escape from the Haunted Castle
        ///
        ///Copyright (C) 2016-2020 Ishan Pranav
        ///
        ///Deluxe Edition | 2020 Revision | Version 3.6x
        ///
        ///For Microsoft(R) Windows XP and higher
        ///
        ///
        ///=== SOFTWARE NOTICE ===
        ///
        ///Escape from the Haunted Castle is an exciting text
        ///adventure game created by Ishan Pranav, with
        ///primary development occurring betwen the years
        ///2016 and 2017 and major enhancements added in 2019
        ///and 2020. The game&apos;s original prototype was
        ///written in the Microsoft CMD/Batc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string README {
            get {
                return ResourceManager.GetString("README", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///``!!````!!````!!!!!!!!````!!````!!````!!!```!!````!!!!!!!!````!!!!!!!!````!!!!!!!`
        ///``!!````!!````!!````!!````!!````!!````!!!!``!!```````!!```````!!``````````!!````!!
        ///``!!!!!!!!````!!!!!!!!````!!````!!````!!`!!`!!```````!!```````!!!!!!!!````!!````!!
        ///``!!````!!````!!````!!````!!````!!````!!``!!!!```````!!```````!!``````````!!````!!
        ///``!!````!!````!!````!!````!!!!!!!!````!!```!!!```````!!```````!!!!!!!!````!!!!!!!
        ///`````````````````````````````````````````````````````````````````````````````````
        ///```````` [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TitleText {
            get {
                return ResourceManager.GetString("TitleText", resourceCulture);
            }
        }
    }
}
