//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HauntedCastle.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Examine {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Examine() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HauntedCastle.Strings.Examine", typeof(Examine).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A crisp, juicy, red apple.@ There are seeds inside..
        /// </summary>
        internal static string apple {
            get {
                return ResourceManager.GetString("apple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two soft leather armchairs..
        /// </summary>
        internal static string armchairs {
            get {
                return ResourceManager.GetString("armchairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A green leather-bound atlas with yellowed pages and maps.@ There is writing inside.@ This atlas seems strange..
        /// </summary>
        internal static string atlas {
            get {
                return ResourceManager.GetString("atlas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sturdy wooden bars..
        /// </summary>
        internal static string bars {
            get {
                return ResourceManager.GetString("bars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tall, green beanstalk surrounded by oak trees..
        /// </summary>
        internal static string beanstalk {
            get {
                return ResourceManager.GetString("beanstalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A flat bed..
        /// </summary>
        internal static string bed {
            get {
                return ResourceManager.GetString("bed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A large bird with a@ particularly long feather portruding from its back..
        /// </summary>
        internal static string bird {
            get {
                return ResourceManager.GetString("bird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A juicy wild blackberry that is probably not safe to eat..
        /// </summary>
        internal static string blackberry {
            get {
                return ResourceManager.GetString("blackberry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A large carboard box.@ It is empty..
        /// </summary>
        internal static string box {
            get {
                return ResourceManager.GetString("box", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slices of white bread covered with garlic..
        /// </summary>
        internal static string bread {
            get {
                return ResourceManager.GetString("bread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twisting rows of tall bushes covered in leaves..
        /// </summary>
        internal static string bushes {
            get {
                return ResourceManager.GetString("bushes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An old wax candle..
        /// </summary>
        internal static string candle {
            get {
                return ResourceManager.GetString("candle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A standard 52-card deck of playing cards without jokers..
        /// </summary>
        internal static string cards {
            get {
                return ResourceManager.GetString("cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A dimly lit castle mostly made of stone.@ Its walls are solid and cannot be burned or broken.@ The castle is haunted by ghosts, goblins, and other foul creatures..
        /// </summary>
        internal static string castle {
            get {
                return ResourceManager.GetString("castle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifty cherry wood chairs..
        /// </summary>
        internal static string chairs {
            get {
                return ResourceManager.GetString("chairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A beautiful crystal chandelier..
        /// </summary>
        internal static string chandelier {
            get {
                return ResourceManager.GetString("chandelier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A piece of moldy cheese.@ Only the nastiest creatures would eat it..
        /// </summary>
        internal static string cheese {
            get {
                return ResourceManager.GetString("cheese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A large wooden chest.@ It is closed..
        /// </summary>
        internal static string chest {
            get {
                return ResourceManager.GetString("chest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A mug filled with coffee.@ It looks delicious, but an odd feeling warns you not to drink it..
        /// </summary>
        internal static string coffee {
            get {
                return ResourceManager.GetString("coffee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four Roman columns with intricate details carved in the white marble..
        /// </summary>
        internal static string columns {
            get {
                return ResourceManager.GetString("columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A gold pocket compass.@ The compass needle points north..
        /// </summary>
        internal static string compass {
            get {
                return ResourceManager.GetString("compass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Razorteeth Studios Personal computer.@ It is turned off..
        /// </summary>
        internal static string computer {
            get {
                return ResourceManager.GetString("computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An orange cookbook with a picture of tomato soup on its cover.@ There is a recipe and writing inside..
        /// </summary>
        internal static string cookbook {
            get {
                return ResourceManager.GetString("cookbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A simple white counter..
        /// </summary>
        internal static string counter {
            get {
                return ResourceManager.GetString("counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A large wooden crate.@ It is empty..
        /// </summary>
        internal static string crate {
            get {
                return ResourceManager.GetString("crate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiny breadcrumbs..
        /// </summary>
        internal static string crumbs {
            get {
                return ResourceManager.GetString("crumbs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A huge, green cyclops with one eye..
        /// </summary>
        internal static string cyclops {
            get {
                return ResourceManager.GetString("cyclops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An oak wood desk..
        /// </summary>
        internal static string desk {
            get {
                return ResourceManager.GetString("desk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A glass display case.@ There is an oil lamp inside..
        /// </summary>
        internal static string display_case {
            get {
                return ResourceManager.GetString("display_case", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A heavy door made of gold and embedded@ with jewels and other precious items.@ It is closed..
        /// </summary>
        internal static string door {
            get {
                return ResourceManager.GetString("door", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large and wooden double doors with gilded handles.@ They are closed..
        /// </summary>
        internal static string doors {
            get {
                return ResourceManager.GetString("doors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A wooden doorway with an intricately carved pattern..
        /// </summary>
        internal static string doorway {
            get {
                return ResourceManager.GetString("doorway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An immense, fire-breathing dragon..
        /// </summary>
        internal static string dragon {
            get {
                return ResourceManager.GetString("dragon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A massive wooden drawbridge..
        /// </summary>
        internal static string drawbridge {
            get {
                return ResourceManager.GetString("drawbridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A drive accepting a 3 1/2-inch floppy disk.@ You will not be able to insert a diskette, as the drive is jammed.@ It can only be opened once before it breaks completely.@ It is closed..
        /// </summary>
        internal static string drive {
            get {
                return ResourceManager.GetString("drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A monolithic steel elevator..
        /// </summary>
        internal static string elevator {
            get {
                return ResourceManager.GetString("elevator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A mysterious elf wearing a red suit and red hat..
        /// </summary>
        internal static string elf {
            get {
                return ResourceManager.GetString("elf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A long white feather with a sharp point..
        /// </summary>
        internal static string feather {
            get {
                return ResourceManager.GetString("feather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A figurehead depicting a majestic horse.@ It is securely fastened to the bowsprit..
        /// </summary>
        internal static string figurehead {
            get {
                return ResourceManager.GetString("figurehead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A standard (but outdated) 3 1/2-inch diskette. @ There is writing on it..
        /// </summary>
        internal static string floppy_disk {
            get {
                return ResourceManager.GetString("floppy_disk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An masterfully carved wooden flute.@ It has magical capabilities..
        /// </summary>
        internal static string flute {
            get {
                return ResourceManager.GetString("flute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shiny gold..
        /// </summary>
        internal static string gold {
            get {
                return ResourceManager.GetString("gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A hook..
        /// </summary>
        internal static string hook {
            get {
                return ResourceManager.GetString("hook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your colorful gingerbread house..
        /// </summary>
        internal static string house {
            get {
                return ResourceManager.GetString("house", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A wooden door marked K.@ It is closed..
        /// </summary>
        internal static string k {
            get {
                return ResourceManager.GetString("k", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A small kettle made of porcelain.@ The kettle contains tea..
        /// </summary>
        internal static string kettle {
            get {
                return ResourceManager.GetString("kettle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tiny silver key..
        /// </summary>
        internal static string key {
            get {
                return ResourceManager.GetString("key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A wooden door marked L..
        /// </summary>
        internal static string l {
            get {
                return ResourceManager.GetString("l", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sturdy wooden ladder..
        /// </summary>
        internal static string ladder {
            get {
                return ResourceManager.GetString("ladder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A small leather bag capable of holding some liquids and solids.@ It is closed..
        /// </summary>
        internal static string leather_bag {
            get {
                return ResourceManager.GetString("leather_bag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A short leprechaun with a little green hat..
        /// </summary>
        internal static string leprechaun {
            get {
                return ResourceManager.GetString("leprechaun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A massive limestone gate, three stories high..
        /// </summary>
        internal static string limestone_gate {
            get {
                return ResourceManager.GetString("limestone_gate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It radiates with magic energy..
        /// </summary>
        internal static string magic_staff {
            get {
                return ResourceManager.GetString("magic_staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The main mast of the ship, an impressive 16 m tall..
        /// </summary>
        internal static string mast {
            get {
                return ResourceManager.GetString("mast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An ordinary match..
        /// </summary>
        internal static string match {
            get {
                return ResourceManager.GetString("match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You see an ugly person staring back at you, @ framed within the large, round mirror..
        /// </summary>
        internal static string mirror {
            get {
                return ResourceManager.GetString("mirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A large, round, talking mirror.@ You see no reflection..
        /// </summary>
        internal static string mirrorInvisible {
            get {
                return ResourceManager.GetString("mirrorInvisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An old-fashioned glass eyepiece..
        /// </summary>
        internal static string monocle {
            get {
                return ResourceManager.GetString("monocle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A black-and-white copy of the Haunted Herald.@ A cartoonist&apos;s representation of you is on the front page.@ There is writing on the newspaper..
        /// </summary>
        internal static string newspaper {
            get {
                return ResourceManager.GetString("newspaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A forest of ancient oak trees..
        /// </summary>
        internal static string oak_trees {
            get {
                return ResourceManager.GetString("oak_trees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tall, white observatory building..
        /// </summary>
        internal static string observatory {
            get {
                return ResourceManager.GetString("observatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An ancient Arabian oil lamp.@ A lazy, unhelpful genie inhabits the lamp and serves its owner..
        /// </summary>
        internal static string oil_lamp {
            get {
                return ResourceManager.GetString("oil_lamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A large oriental rug woven from silk.@ It is thick and heavy..
        /// </summary>
        internal static string oriental_rug {
            get {
                return ResourceManager.GetString("oriental_rug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A red book filled with poetry.@ There is writing inside..
        /// </summary>
        internal static string poetry {
            get {
                return ResourceManager.GetString("poetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An immense forest with trees on all sides..
        /// </summary>
        internal static string rainforest {
            get {
                return ResourceManager.GetString("rainforest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three nasty rats..
        /// </summary>
        internal static string rats {
            get {
                return ResourceManager.GetString("rats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A recipe for tomato soup, taken from a cookbook..
        /// </summary>
        internal static string recipe {
            get {
                return ResourceManager.GetString("recipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A long, thin rope..
        /// </summary>
        internal static string rope {
            get {
                return ResourceManager.GetString("rope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A small, round secret door.@ It blends in with the library wall..
        /// </summary>
        internal static string secret_door {
            get {
                return ResourceManager.GetString("secret_door", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seeds from a red apple..
        /// </summary>
        internal static string seeds {
            get {
                return ResourceManager.GetString("seeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tall and empty cherry wood shelf..
        /// </summary>
        internal static string shelf {
            get {
                return ResourceManager.GetString("shelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A round, flat shield made of silver..
        /// </summary>
        internal static string shield {
            get {
                return ResourceManager.GetString("shield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A distant sailing ship..
        /// </summary>
        internal static string ship2 {
            get {
                return ResourceManager.GetString("ship2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shiny silver from a melted key..
        /// </summary>
        internal static string silver {
            get {
                return ResourceManager.GetString("silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A double basin, stainless steel sink..
        /// </summary>
        internal static string sink {
            get {
                return ResourceManager.GetString("sink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A massive snake with menacing patterns along its long body.@ Sharp, vicious fangs extend out from its huge jaws..
        /// </summary>
        internal static string snake {
            get {
                return ResourceManager.GetString("snake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A brown leather-bound spellbook with yellowed pages.@ There is writing inside..
        /// </summary>
        internal static string spellbook {
            get {
                return ResourceManager.GetString("spellbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A majestic sphinx with a human head and the body of a lion..
        /// </summary>
        internal static string sphinx {
            get {
                return ResourceManager.GetString("sphinx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparent saliva..
        /// </summary>
        internal static string spit {
            get {
                return ResourceManager.GetString("spit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An elevated theater stage..
        /// </summary>
        internal static string stage {
            get {
                return ResourceManager.GetString("stage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White marble steps..
        /// </summary>
        internal static string steps {
            get {
                return ResourceManager.GetString("steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An stainless steel four-burner stove..
        /// </summary>
        internal static string stove {
            get {
                return ResourceManager.GetString("stove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A strange blue book glowing with energy.@ There is writing inside, but the book is locked..
        /// </summary>
        internal static string strange_purple {
            get {
                return ResourceManager.GetString("strange_purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A long, rectangular cherry wood table used for fine dining..
        /// </summary>
        internal static string table {
            get {
                return ResourceManager.GetString("table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A small, rectangular table made of wood..
        /// </summary>
        internal static string table2 {
            get {
                return ResourceManager.GetString("table2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An ornate golden throne engraved with intricate carvings..
        /// </summary>
        internal static string throne {
            get {
                return ResourceManager.GetString("throne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fresh, juicy, red tomatoes..
        /// </summary>
        internal static string tomatoes {
            get {
                return ResourceManager.GetString("tomatoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An ugly, beige troll with red eyes..
        /// </summary>
        internal static string troll {
            get {
                return ResourceManager.GetString("troll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A long, narrow feeding trough providing water for horses..
        /// </summary>
        internal static string trough {
            get {
                return ResourceManager.GetString("trough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A dark and eerie tunnel..
        /// </summary>
        internal static string tunnel {
            get {
                return ResourceManager.GetString("tunnel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A pale vampire capable of transforming into a bat..
        /// </summary>
        internal static string vampire {
            get {
                return ResourceManager.GetString("vampire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordinary tap water.@ It has a slight golden shine..
        /// </summary>
        internal static string water {
            get {
                return ResourceManager.GetString("water", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A terrifying werewolf..
        /// </summary>
        internal static string werewolf {
            get {
                return ResourceManager.GetString("werewolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The wooden steering wheel of the ship, supported by a pedestal.@ The wheel has eight handles..
        /// </summary>
        internal static string wheel {
            get {
                return ResourceManager.GetString("wheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A glass window.@ A perilous abyss lies behind it.@ The window is closed..
        /// </summary>
        internal static string window {
            get {
                return ResourceManager.GetString("window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A wooden door marked X..
        /// </summary>
        internal static string x {
            get {
                return ResourceManager.GetString("x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A wooden door marked Y..
        /// </summary>
        internal static string y {
            get {
                return ResourceManager.GetString("y", resourceCulture);
            }
        }
    }
}
